version: '3.9'

services:
  # API Gateway
  gateway:
    container_name: gateway
    build: .
    ports:
      - "8080:8080"
    networks:
      - Time

# Docker Networks
networks:
  Time:
      name: Time
      external: true
      
# ///////////////////////////////////////////
# Docker Volumes
volumes:
  db:
  mongo-data: